"""index to slug added

Revision ID: 3f59d6d15b4a
Revises: 65cfafb3e6a3
Create Date: 2025-06-30 13:11:03.046915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f59d6d15b4a'
down_revision: Union[str, Sequence[str], None] = '65cfafb3e6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pastes_slug_key'), 'pastes', type_='unique')
    op.create_index(op.f('ix_pastes_slug'), 'pastes', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pastes_slug'), table_name='pastes')
    op.create_unique_constraint(op.f('pastes_slug_key'), 'pastes', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
